---

install: false
open_files_limit: 1024000

mysql_config:
  client:
    - port: '3306'
    - socket: '/var/run/mariadb/mysqld.sock'
  mysqld_safe:
    - socket: '/var/run/mariadb/mysqld.sock'
    - nice: '0'
    - open_files_limit: '{{ open_files_limit }}'
  mysqld:
    - back_log: '300'
    - binlog_format: 'MIXED'
    - character-set-server: 'utf8'
    - collation-server: 'utf8_unicode_ci'
    - datadir: '/var/lib/mysql'
    - expire_logs_days: '14'
    - group_concat_max_len: '4294967295'
    - init-connect: 'SET NAMES utf8'
    - innodb_buffer_pool_size: '{{ (ansible_memtotal_mb * 0.5) | int }}M'
    - innodb_file_per_table: '0'
    - innodb_flush_log_at_trx_commit: '2'
    - innodb_lock_wait_timeout: '120'
    - innodb_log_buffer_size: '256M'
    - innodb_log_file_size: '48M'
    - innodb_open_files: '1024000'
    - innodb_stats_on_metadata: '0'
    - innodb_thread_concurrency: '0'
    - join_buffer_size: '256K'
    - key_buffer_size: '32M'
    - log_bin_trust_function_creators: '1'
    - log-error: '/var/log/mariadb/error.log'
    - max_allowed_packet: '512M'
    - max_binlog_size: '1073741824'
    - max_connect_errors: '2000'
    - max_connections: '1000'
    - myisam-recover-options: 'BACKUP'
    - pid-file: '/var/run/mariadb/mariadb.pid'
    - port: '3306'
    - query_cache_limit: '1M'
    - query_cache_size: '12M'
    - read_buffer_size: '256K'
    - read_rnd_buffer_size: '256K'
    - report-host: '{{ ansible_hostname }}'
    - relay_log_index: 'mysqld-relay-bin.index'
    - server-id: "{{ ansible_default_ipv4.address.split('.')[3] }}"
    - skip-external-locking
    - skip_name_resolve
    - socket: '/var/run/mariadb/mysqld.sock'
    - sort_buffer_size: '256K'
    - sync_binlog: '1'
    - table_open_cache: '2000'
    - thread_cache_size: '32'
    - thread_stack: '256K'
    - tmp_table_size: '24M'
    - tmpdir: '/tmp'
    - user: 'mysql'
    - open_files_limit: '{{ open_files_limit }}'
    - sql_mode: 'STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER,ERROR_FOR_DIVISION_BY_ZERO'
  mysqldump:
    - quick
    - quote-names
    - max_allowed_packet: '16M'
  isamchk:
    key_buffer: '16M'
  mysql:
    - no-auto-rehash
  myisamchk:
    key_buffer_size : '8M'
    sort_buffer_size : '8M'
  mysqlhotcopy:
    - interactive-timeout

#
# Role vars for mariadb role
#

mariadb_role_name: 'mariadb'
mariadb_root_password: 'rootPasswd'
mysql_user: mysql
mysql_service_path: "/etc/systemd/system/mysqld@.service"
mysqld_multi_path: "/usr/bin/mysqld_multi"
