---

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: stop & disable firewalld.service
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no
  when: gui_enabled
